In [299]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns
import statsmodels.api as sm
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler

In [300]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [301]:
file = pd.read_csv('column_3C.dat', sep=' ', index_col = None, header = None, encoding = 'ascii')

In [353]:
df = pd.DataFrame(file)

In [354]:
df = df.dropna()
#Mapping int values to each string on the label
mymap = {'DH':1, 'NO':0, 'SL':2}
kdf= df.applymap(lambda s: mymap.get(s) if s in mymap else s)
kdf = kdf.sample(frac=1).reset_index(drop=True)# Shuffle the data so the model recognizes the multiclass output

In [355]:
kdf

0      1       2       3       4       5  6
0     57.04   0.35   49.20   56.69  103.05   52.17  2
1     81.08  21.26   78.77   59.83   90.07   49.16  2
2     74.57  15.72   58.62   58.84  105.42    0.60  0
3     84.97  33.02   60.86   51.95  125.66   74.33  2
4     63.07  24.41   54.00   38.66  106.42   15.78  1
5     92.03  35.39   77.42   56.63  115.72   58.06  2
6     69.63  21.12   52.77   48.50  116.80   54.82  2
7     50.09  13.43   34.46   36.66  119.13    3.09  0
8     69.78  13.78   58.00   56.00  118.93   17.91  2
9     58.78   7.67   53.34   51.12   98.50   51.58  2
10    70.48  12.49   62.42   57.99  114.19   56.90  2
11    55.29  20.44   34.00   34.85  115.88    3.56  1
12    47.32   8.57   35.56   38.75  120.58    1.63  0
13    40.68   9.15   31.02   31.53  139.12   -2.51  0
14    53.43  15.86   37.17   37.57  120.57    5.99  1
15    56.56   8.96   52.58   47.60   98.78   50.70  2
16    70.22  39.82   68.12   30.40  148.53  145.38  2
17    60.75  15.75   43.20   45.00  113.05   31.69  2
18    80.65  26.34   60.90   54.31  120.10   52.47  2
19    56.54  14.38   44.99   42.16  101.72   25.77  2
20    72.96  19.58   61.01   53.38  111.23    0.81  0
21    72.34  16.42   59.87   55.92   70.08   12.07  2
22    68.72  49.43   68.06   19.29  125.02   54.69  2
23    77.69  21.38   64.43   56.31  114.82   26.93  2
24    46.39  11.08   32.14   35.31   98.77    6.39  1
25    49.83  16.74   28.00   33.09  121.44    1.91  0
26    56.03  16.30   62.28   39.73  114.02   -2.33  1
27    43.20  19.66   35.00   23.54  124.85   -2.92  1
28    36.69   5.01   41.95   31.68   84.24    0.66  1
29    61.54  19.68   52.89   41.86  118.69    4.82  0
30    89.83  22.64   90.56   67.20  100.50    3.04  0
31    74.98  14.92   53.73   60.05  105.65    1.59  0
32    48.03   3.97   58.34   44.06  125.35   35.00  2
33    80.82  19.24   61.64   61.58   89.47   44.17  2
34    34.76   2.63   29.50   32.12  127.14   -0.46  0
35    45.44   9.91   45.00   35.54  163.07   20.32  2
36    83.40  34.31   78.42   49.09  110.47   49.67  2
37    51.53  13.52   35.00   38.01  126.72   13.93  0
38    84.59  30.36   65.48   54.22  108.01   25.12  2
39    74.43  41.56   27.70   32.88  107.95    5.00  1
40    65.01   9.84   57.74   55.18   94.74   49.70  2
41    60.63  20.60   64.54   40.03  117.23  104.86  2
42    51.62  15.97   35.00   35.66  129.39    1.01  0
43    56.61  16.80   42.00   39.81  127.29   24.02  2
44    53.91  12.94   39.00   40.97  118.19    5.07  0
45    63.93  19.97   40.18   43.96  113.07  -11.06  0
46    87.68  20.37   93.82   67.31  120.94   76.73  2
47    76.31  41.93   93.28   34.38  132.27  101.22  2
48    68.83  22.22   50.09   46.61  105.99   -3.53  1
49    85.35  15.84   71.67   69.51  124.42   76.02  2
50    55.08  -3.76   56.00   58.84  109.92   31.77  2
51    35.88   1.11   43.46   34.77  126.92   -1.63  0
52    82.41  29.28   77.05   53.13  117.04   62.77  2
53    64.62  15.23   67.63   49.40   90.30   31.33  2
54    66.88  24.89   49.28   41.99  113.48   -2.01  1
55    78.49  22.18   60.00   56.31  118.53   27.38  2
56    48.33  22.23   36.18   26.10  117.38    6.48  1
57    72.64  18.93   68.00   53.71  116.96   25.38  2
58    57.52  33.65   50.91   23.88  140.98  148.75  2
59    94.17  15.38   67.71   78.79  114.89   53.26  2
60    45.54  13.07   30.30   32.47  117.98   -4.99  1
61    65.61  23.14   62.58   42.47  124.13   -4.08  0
62    45.58  18.76   33.77   26.82  116.80    3.13  0
63    55.84  28.85   47.69   27.00  123.31    2.81  1
64    70.95  20.16   62.86   50.79  116.18   32.52  2
65    69.30  24.65   44.31   44.64  101.87   11.21  1
66    64.81  15.17   58.84   49.64  111.68   21.41  2
67    80.11  33.94   85.10   46.17  125.59  100.29  2
68    50.75  20.24   37.00   30.52  122.34    2.29  0
69    50.07   9.12   32.17   40.95   99.71   26.77  2
70    52.42  19.01   35.87   33.41  116.56    1.69  1
71    48.17   9.59   39.71   38.58  135.62    5.36  0
72   129.83   8.40   48.38  121.43  107.69  418.54  2
73    61.73  1

In [356]:
features = kdf.loc[:,0:5] # selecting feature_data
labels = kdf.loc[:,6] # selecting the label data
min_max_scaler = preprocessing.MinMaxScaler() #Normalizing the feature data 
features = min_max_scaler.fit_transform(features)
kdff = pd.DataFrame(features)

In [357]:
labels.shape

(310,)

In [375]:
# Splitting the data to training and testing
train_features = kdff[0:250]
test_features = kdff[250:]
train_labels = labels[0:250]
test_labels = labels[250:]


In [376]:
print(train_features.shape)
print(test_features.shape)
print(train_labels.shape)
print(test_labels.shape)

(250, 6)
(60, 6)
(250,)
(60,)


In [377]:
model = LogisticRegression().fit(train_features, train_labels)

In [378]:
print("Coefficients: ",model.coef_)
print("Intercept: ", model.intercept_)

Coefficients:  [[-0.32131196 -1.33426785 -0.65141755  0.3824948   2.12495007 -1.92907306]
 [-1.43146191  1.30442673 -2.0335792  -2.04903697 -0.97562068 -1.00442468]
 [ 1.75277387  0.02984112  2.68499676  1.66654217 -1.14932938  2.93349774]]
Intercept:  [-0.03828537  1.16628253 -1.12799716]


In [379]:

Y_pred = model.predict(train_features)

In [380]:
cm = confusion_matrix(train_labels, Y_pred)
print("Confusion matrix:\n",cm)

accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
print("Accuracy calculated from the training set = %.3f" % (accuracy))

print(classification_report(train_labels, Y_pred,target_names=['no', 'yes','maybe']))

Confusion matrix:
 [[ 63   3  16]
 [ 21  19   8]
 [ 11   1 108]]
Accuracy calculated from the training set = 0.774
              precision    recall  f1-score   support

          no       0.66      0.77      0.71        82
         yes       0.83      0.40      0.54        48
       maybe       0.82      0.90      0.86       120

    accuracy                           0.76       250
   macro avg       0.77      0.69      0.70       250
weighted avg       0.77      0.76      0.75       250



In [381]:
model1 = LogisticRegression().fit(train_features, train_labels)

In [382]:
pred = model1.predict(test_features)
print(classification_report(test_labels, pred,target_names=['no', 'yes','maybe']))

              precision    recall  f1-score   support

          no       0.64      0.78      0.70        18
         yes       0.83      0.42      0.56        12
       maybe       0.88      0.93      0.90        30

    accuracy                           0.78        60
   macro avg       0.78      0.71      0.72        60
weighted avg       0.80      0.78      0.77        60



# From the classification report above.. there was a undefinedmetricwarning when trying to predict the test_data. 
This was fixed by shuffling the data since the labels where in an ordered form which makes it difficult for the model to learn.

# Predicting the train/test data outputs a 3x3 confusion matrix

In [374]:
model1.predict_proba(test_features)

array([[0.48952807, 0.32498004, 0.18549189],
       [0.64278   , 0.25154382, 0.10567618],
       [0.49436141, 0.2054739 , 0.30016469],
       [0.68472984, 0.18050867, 0.13476148],
       [0.06462799, 0.04543385, 0.88993817],
       [0.52399706, 0.36358248, 0.11242046],
       [0.29869586, 0.1027939 , 0.59851023],
       [0.31079581, 0.54679067, 0.14241352],
       [0.16475184, 0.11031341, 0.72493474],
       [0.30051335, 0.10665993, 0.59282672],
       [0.16388255, 0.11915944, 0.71695801],
       [0.48315292, 0.09035122, 0.42649586],
       [0.62690492, 0.28394759, 0.08914749],
       [0.1159799 , 0.03012612, 0.85389398],
       [0.4107377 , 0.43400521, 0.15525709],
       [0.50862204, 0.30565374, 0.18572422],
       [0.12505117, 0.01876421, 0.85618462],
       [0.43755451, 0.31442886, 0.24801663],
       [0.72658199, 0.16847446, 0.10494355],
       [0.37286043, 0.17410684, 0.45303272],
       [0.50606072, 0.19217474, 0.30176454],
       [0.04731882, 0.00622493, 0.94645625],
       [0.